
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 25 04:51:20 CEST 2015
//----------------------------------------------------

package rs.ac.bg.etf.ln110181d;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 17;
  public static final int LBRACKET = 41;
  public static final int CONST = 6;
  public static final int LESSE = 32;
  public static final int GRT = 29;
  public static final int LPAREN = 39;
  public static final int SEMI = 36;
  public static final int LESS = 31;
  public static final int RPAREN = 40;
  public static final int COMMA = 37;
  public static final int CLASS = 4;
  public static final int INC = 25;
  public static final int DIV = 23;
  public static final int ASSIGN = 35;
  public static final int IF = 7;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int LAND = 33;
  public static final int RETURN = 11;
  public static final int RBRACKET = 42;
  public static final int GRTE = 30;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 22;
  public static final int LOR = 34;
  public static final int ADD = 20;
  public static final int NUMBER = 16;
  public static final int MOD = 24;
  public static final int NEQ = 28;
  public static final int BREAK = 3;
  public static final int IDENT = 15;
  public static final int VOID = 12;
  public static final int EQ = 27;
  public static final int LBRACE = 43;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int WHILE = 13;
  public static final int RBRACE = 44;
  public static final int EXTENDS = 14;
  public static final int BOOL_CONST = 18;
  public static final int DEC = 26;
  public static final int STRING_CONST = 19;
  public static final int SUB = 21;
  public static final int PRINT = 9;
}

